apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-upgrade-test
  namespace: dbs-qa
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    zerbino: []  # role for application foo
    ezra: []
  databases:
    foo: zalando  # dbname: owner
    scarpa: zerbino
    log: ezra
  preparedDatabases:
    bar: {}
  postgresql:
    version: "12"
    parameters:
      max_connections: "1000"
